package  com.barry.drools.mapAndList
import com.barry.drools.bean.Person;
import  com.barry.drools.bean.Car;
import  com.barry.drools.mapAndList.SubPerson;

rule "insertTest1"
salience 10
when

then
Person person=new Person("分享牛",18);
insert(person);
    System.out.println("insertTest1被触发");
 end

rule "insertTest2"
salience 5
lock-on-active true
when
    $p:Person(age==18)
then
    System.out.println("insertTest2被触发："+$p);
    Person person=new Person("分享牛",25);
    insert(person);
 end


rule "insertTest3"
when
    $p:Person(age==25)
then
    System.out.println("insertTest3被触发："+$p);
 end
