package  com.barry.drools.ch10
import  java.util.Date;


rule "new-type-rule-1"
salience 10
when
    $country:Country(name=="中国")
then
    System.out.println("declare被触发,");
    Address address=new Address();
    address.setCity("北京");
    address.setNumber(123);
    address.setName("北京");
    insert(address);
 end

rule "declareRule2"
salience 1
when
    $address:Address(name==CountryName.CHINA.getFullName())
then
   System.out.println("declareRule2被触发,");
 end



 declare Country
    name:String
 end
 declare  Address extends Country
      number:Integer
      city:String
      createTine:Date
 end

declare enum CountryName
    CHINA("北京");
    fullName : String
end










