package  com.barry.drools.ch10
import com.barry.drools.bean.Person;
import  com.barry.drools.bean.Car;
import  com.barry.drools.mapAndList.SubPerson;
import  java.lang.Integer;
rule "functionRule1"
salience 10
when
    $p1:Person()
then
    System.out.println("functionRule1被触发,"+$p1);
    hello();
    hello2("functionRule1");
 end
function  void hello(){
System.out.println("hello function");

}

function  String hello2( String name){
return  "hello2"+name;

}








