package  com.barry.drools.ch10
import com.barry.drools.bean.Person;
import  com.barry.drools.bean.Car;
import  com.barry.drools.mapAndList.SubPerson;

//rule "updateRule1"
//salience 10
//when
//    $p:Person(age==24)
//then
//    System.out.println("updateRule1被触发,"+$p);
//    $p.setAge(28);
// //   update($p)
// end
//
//
//
//rule "updateRule2"
//salience 5
//when
//    $p:Person(age==28)
//then
//    System.out.println("updateRule2被触发,"+$p);
// end

