package  com.barry.drools.ch10
import com.barry.drools.bean.Person;
import  com.barry.drools.bean.Car;
import  com.barry.drools.mapAndList.SubPerson;
//
//rule "deleteRule1"
//salience 10
//when
//    $p:Person(age==24)
//then
//    System.out.println("deleteRule1被触发,"+$p);
//   // delete($p);
// end
//
//rule "deleteRule2"
//salience 1
//when
//    $p:Person()
//then
//    System.out.println("deleteRule2被触发,"+$p);
// end




